# ==========================================================
# PRODUCTION PROFILE
# ==========================================================

# Name of the production application.
spring.application.name=book-api-prod


# ----------------------------------------------------------
# DATABASE CONFIGURATION
# ----------------------------------------------------------

# Production database URL.
#
# This is an example.
# In a real project, this would point to the production DB.
spring.datasource.url=url=jdbc:mysql://localhost:3306/day10_book_db


# Production database username.
spring.datasource.username=root


# Production database password.
spring.datasource.password=root


# MySQL JDBC driver.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ----------------------------------------------------------
# JPA / HIBERNATE
# ----------------------------------------------------------

# NEVER automatically change the production schema.
#
# "validate" checks whether the database structure
# matches the entity structure.
spring.jpa.hibernate.ddl-auto=validate


# Don't print SQL queries in production.
spring.jpa.show-sql=true


# ----------------------------------------------------------
# LOGGING
# ----------------------------------------------------------

# Production normally uses INFO logging.
logging.level.Day_9=INFO


# Spring web logging.
logging.level.org.springframework.web=WARN