]# ==========================================================
# COMMON APPLICATION CONFIGURATION
# ==========================================================

# This tells Spring Boot which profile should be active.
#
# "dev" means Spring will also load:
#
# application-dev.properties
#
# Later, we can change this to "prod".
spring.profiles.active=dev